basePath: /
host: localhost:8080
info:
  contact:
    email: support@brb.com
    name: API Support
    url: http://www.brb.com/support
  description: This is a microservice for managing services, vendors, and bookings.
  title: BRB Mid Service Platform API
  version: "1.0"
paths: {}
swagger: "2.0"
